"""
PostgreSQL database layer.

Handles connection setup, schema creation, and CRUD operations for QA pairs.

Table: qa_pairs
  id                TEXT PRIMARY KEY  (deterministic: uuid5 of cube:question)
  cube_name         VARCHAR
  question          TEXT
  mdx               TEXT (nullable when ENABLE_MDX_GENERATION=false)
  complexity        VARCHAR
  dimensions_used   JSONB
  measures_used     JSONB
  langfuse_trace_id VARCHAR (nullable)
  feedback          VARCHAR(20) (null | 'positive' | 'negative')
  created_at        TIMESTAMP
"""

import json
import logging
import uuid

import psycopg2
import psycopg2.extras

from backend.config import settings
from backend.models.schemas import QAPair, ComplexityLevel

logger = logging.getLogger(__name__)

# Deterministic namespace — same as uploader_agent so IDs match across both stores
_NS = uuid.NAMESPACE_DNS


def _make_id(cube_name: str, question: str) -> str:
    """Return a deterministic UUID string for a (cube, question) pair.
    
    IMPORTANT: must use double-colon separator ('::') to match the ID
    generated by QdrantUploaderAgent._make_id() so PostgreSQL and Qdrant
    reference the same records.
    """
    return str(uuid.uuid5(_NS, f"{cube_name}::{question}"))


# ── Connection ────────────────────────────────────────────────────────────────

def get_connection():
    """Return a new psycopg2 connection. Caller is responsible for closing it."""
    return psycopg2.connect(settings.postgres_url)


# ── Schema ────────────────────────────────────────────────────────────────────

def init_db() -> None:
    """
    Create the qa_pairs table and apply any missing columns.
    Safe to call on every startup — uses IF NOT EXISTS guards.
    """
    ddl = """
    CREATE TABLE IF NOT EXISTS qa_pairs (
        id                TEXT PRIMARY KEY,
        cube_name         VARCHAR(255) NOT NULL,
        question          TEXT        NOT NULL,
        mdx               TEXT,
        complexity        VARCHAR(50),
        dimensions_used   JSONB,
        measures_used     JSONB,
        langfuse_trace_id VARCHAR(255),
        feedback          VARCHAR(20),
        created_at        TIMESTAMP   DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_qa_pairs_cube     ON qa_pairs(cube_name);
    CREATE INDEX IF NOT EXISTS idx_qa_pairs_feedback ON qa_pairs(feedback);

    -- Incremental migrations (safe to re-run)
    ALTER TABLE qa_pairs ADD COLUMN IF NOT EXISTS feedback      VARCHAR(20);
    ALTER TABLE qa_pairs ADD COLUMN IF NOT EXISTS user_question TEXT;
    ALTER TABLE qa_pairs ADD COLUMN IF NOT EXISTS entities      JSONB;
    ALTER TABLE qa_pairs ADD COLUMN IF NOT EXISTS mdx_template  TEXT;
    ALTER TABLE qa_pairs ADD COLUMN IF NOT EXISTS entity_map    JSONB;

    -- Query log: every incoming query is recorded here
    CREATE TABLE IF NOT EXISTS query_log (
        id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        question       TEXT NOT NULL,
        user_entities  JSONB,
        matched_id     TEXT REFERENCES qa_pairs(id) ON DELETE SET NULL,
        matched_q      TEXT,
        similarity     FLOAT,
        mismatch       VARCHAR(20),
        action         VARCHAR(20),
        cube_name      VARCHAR(255),
        patched_mdx    TEXT,
        error          TEXT,
        created_at     TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_query_log_action     ON query_log(action);
    CREATE INDEX IF NOT EXISTS idx_query_log_created_at ON query_log(created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_query_log_mismatch   ON query_log(mismatch);
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(ddl)
        conn.commit()
    logger.info("PostgreSQL schema ready (qa_pairs table exists).")


# ── Write ─────────────────────────────────────────────────────────────────────

def save_pairs(pairs: list[QAPair]) -> int:
    """
    Insert QA pairs into PostgreSQL.

    Uses INSERT ... ON CONFLICT DO NOTHING so re-running the pipeline with
    duplicate questions is safe — existing rows are not overwritten.

    Returns the number of rows actually inserted.
    """
    if not pairs:
        return 0

    rows = [
        (
            _make_id(p.cube_name, p.question),
            p.cube_name,
            p.question,
            p.mdx,
            p.complexity.value if p.complexity else None,
            json.dumps(p.dimensions_used or []),
            json.dumps(p.measures_used  or []),
            p.langfuse_trace_id,
            p.mdx_template,
            json.dumps(p.entity_map) if p.entity_map else None,
        )
        for p in pairs
    ]

    sql = """
        INSERT INTO qa_pairs
            (id, cube_name, question, mdx, complexity,
             dimensions_used, measures_used, langfuse_trace_id,
             mdx_template, entity_map)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (id) DO NOTHING
    """

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.executemany(sql, rows)
            inserted = cur.rowcount
        conn.commit()

    logger.info("Saved %d new QA pair(s) to PostgreSQL (skipped duplicates).", inserted)
    return inserted


def save_feedback(question: str, cube_name: str, feedback: str) -> bool:
    """
    Update the feedback field for a QA pair identified by (cube_name, question).

    feedback must be 'positive' or 'negative'.
    Returns True if a row was updated, False if not found.
    """
    pair_id = _make_id(cube_name, question)
    sql = "UPDATE qa_pairs SET feedback = %s WHERE id = %s"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (feedback, pair_id))
            updated = cur.rowcount
        conn.commit()
    logger.info("Feedback '%s' saved for question '%s...'.", feedback, question[:60])
    return updated > 0


def save_feedback_by_id(pair_id: str, feedback: str, user_question: str | None = None) -> bool:
    """
    Update the feedback field (and optionally user_question) for a QA pair.

    user_question stores what the user actually typed — useful for understanding
    why a cached answer was flagged when it differs from the stored question.
    """
    sql = "UPDATE qa_pairs SET feedback = %s, user_question = %s WHERE id = %s"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (feedback, user_question, pair_id))
            updated = cur.rowcount
        conn.commit()
    logger.info("Feedback '%s' saved for pair_id '%s' (user_q: %s).", feedback, pair_id, (user_question or '')[:60])
    return updated > 0


# ── Read ──────────────────────────────────────────────────────────────────────

def load_pairs_for_cube(cube_name: str) -> list[QAPair]:
    """
    Load all stored QA pairs for a cube from PostgreSQL.
    Called by the orchestrator at startup to skip LLM re-generation.
    """
    sql = """
        SELECT question, mdx, complexity, dimensions_used, measures_used,
               langfuse_trace_id
        FROM   qa_pairs
        WHERE  cube_name = %s
        ORDER  BY created_at ASC
    """

    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            cur.execute(sql, (cube_name,))
            rows = cur.fetchall()

    pairs = []
    for row in rows:
        try:
            complexity = ComplexityLevel(row["complexity"]) if row["complexity"] else None
        except ValueError:
            complexity = None

        pairs.append(QAPair(
            question          = row["question"],
            mdx               = row["mdx"] or "",
            cube_name         = cube_name,
            complexity        = complexity,
            dimensions_used   = row["dimensions_used"] or [],
            measures_used     = row["measures_used"]   or [],
            langfuse_trace_id = row["langfuse_trace_id"],
        ))

    logger.info(
        "Loaded %d QA pair(s) from PostgreSQL for cube '%s'.", len(pairs), cube_name
    )
    return pairs


def get_pair_by_id(pair_id: str) -> dict | None:
    """Return the full qa_pair row as a dict, or None if not found."""
    sql = "SELECT id, cube_name, question, mdx FROM qa_pairs WHERE id = %s"
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            cur.execute(sql, (pair_id,))
            row = cur.fetchone()
    return dict(row) if row else None



def get_all_pairs(
    cube_name:    str | None = None,
    feedback:     str | None = None,
    search:       str | None = None,   # keyword in question text
    mdx_search:   str | None = None,   # keyword in MDX content only
    has_template: bool | None = None,
    page:         int = 1,
    page_size:    int = 50,
) -> tuple[list[dict], int]:
    """
    Return a paginated list of QA pairs for the admin cache management UI.

    Filters:
      cube_name    — exact cube name match
      feedback     — 'positive' | 'negative'
      search       — case-insensitive keyword in question text
      mdx_search   — case-insensitive keyword in MDX content (year, country, etc.)
      has_template — True: only rows with mdx_template set

    Returns (rows, total_count).
    """
    conditions: list[str] = []
    params: list = []

    if cube_name:
        conditions.append("cube_name = %s")
        params.append(cube_name)
    if feedback:
        conditions.append("feedback = %s")
        params.append(feedback)
    if search:
        conditions.append("question ILIKE %s")
        params.append(f"%{search}%")
    if mdx_search:
        conditions.append("mdx ILIKE %s")
        params.append(f"%{mdx_search}%")
    if has_template is True:
        conditions.append("mdx_template IS NOT NULL")
    elif has_template is False:
        conditions.append("mdx_template IS NULL")

    where  = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    offset = (page - 1) * page_size

    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            cur.execute(f"SELECT COUNT(*) FROM qa_pairs {where}", params)
            total = cur.fetchone()[0]

            cur.execute(
                f"""
                SELECT id, cube_name, question, mdx, complexity,
                       feedback, user_question, created_at,
                       (mdx_template IS NOT NULL) AS has_template
                FROM   qa_pairs
                {where}
                ORDER  BY created_at DESC
                LIMIT  %s OFFSET %s
                """,
                params + [page_size, offset],
            )
            rows = [dict(r) for r in cur.fetchall()]

    # Convert datetime to ISO string for JSON serialisation
    for row in rows:
        if row.get("created_at"):
            row["created_at"] = row["created_at"].isoformat()

    return rows, total


def count_pairs_for_cube(cube_name: str) -> int:
    """Return the number of stored QA pairs for a cube."""
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) FROM qa_pairs WHERE cube_name = %s", (cube_name,)
            )
            return cur.fetchone()[0]


# ── Update / Delete ───────────────────────────────────────────────────────────

def update_pair_mdx(pair_id: str, new_mdx: str) -> bool:
    """Update MDX and invalidate templates derived from the previous query."""
    sql = """
        UPDATE qa_pairs
        SET mdx = %s, mdx_template = NULL, entity_map = NULL
        WHERE id = %s
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (new_mdx, pair_id))
            updated = cur.rowcount
        conn.commit()
    return updated > 0


def delete_pair(pair_id: str) -> bool:
    """Delete a QA pair from PostgreSQL. Returns True if a row was deleted."""
    sql = "DELETE FROM qa_pairs WHERE id = %s"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (pair_id,))
            deleted = cur.rowcount
        conn.commit()
    return deleted > 0


# ── Query Log ─────────────────────────────────────────────────────────────────

def log_query(
    *,
    question:      str,
    user_entities: dict | None   = None,
    matched_id:    str | None    = None,
    matched_q:     str | None    = None,
    similarity:    float | None  = None,
    mismatch:      str | None    = None,   # none/year/entity/major
    action:        str,                    # hit/patched/miss/failed
    cube_name:     str | None    = None,
    patched_mdx:   str | None    = None,
    error:         str | None    = None,
) -> None:
    """
    Append one row to query_log.
    Non-fatal — if the write fails it is silently skipped.
    """
    import json as _json
    sql = """
        INSERT INTO query_log
            (question, user_entities, matched_id, matched_q, similarity,
             mismatch, action, cube_name, patched_mdx, error)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (
                    question,
                    _json.dumps(user_entities) if user_entities else None,
                    matched_id,
                    matched_q,
                    similarity,
                    mismatch,
                    action,
                    cube_name,
                    patched_mdx,
                    error,
                ))
            conn.commit()
    except Exception as exc:
        logger.warning("log_query failed (non-fatal): %s", exc)


def get_query_log(
    action:    str | None = None,
    mismatch:  str | None = None,
    page:      int = 1,
    page_size: int = 50,
) -> tuple[list[dict], int]:
    """
    Return paginated query log rows, newest first.
    Optionally filter by action (hit/patched/miss/failed) or mismatch type.
    """
    conditions = []
    params: list = []
    if action:
        conditions.append("action = %s");   params.append(action)
    if mismatch:
        conditions.append("mismatch = %s"); params.append(mismatch)

    where = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    offset = (page - 1) * page_size

    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            cur.execute(f"SELECT COUNT(*) FROM query_log {where}", params)
            total = cur.fetchone()[0]
            cur.execute(
                f"""
                SELECT id, question, user_entities, matched_id, matched_q,
                       similarity, mismatch, action, cube_name, patched_mdx,
                       error, created_at
                FROM   query_log {where}
                ORDER  BY created_at DESC
                LIMIT  %s OFFSET %s
                """,
                params + [page_size, offset],
            )
            rows = [dict(r) for r in cur.fetchall()]

    for r in rows:
        if r.get("created_at"):
            r["created_at"] = r["created_at"].isoformat()

    return rows, total
